### ISSUE TITLE
can't find external program python.exe terraform

### ISSUE THREAD

**Issue by jsepulveda82** [camptocamp/terraform-aws-rds-nlb#3]
Hello, I was using this module and it had this error **can't find external program python.exe terraform**. It was because in package.tf on line 2 was "python.exe" as the program to use. It worked changing it by "py".

It is possible to be changed in the source?

thanks!

**Comment by saimonn** [comment]
There is currently no `packages.tf` file in this repository, I guess it may come from an external dependency and can't be fixed inside this project.
Please re-open this issue with a link to the mentioned file if I'm wrong.
